---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacassandra0-default
  namespace: default
  labels:
    app: cassandra
    namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/dotricorder03/data-cassandra-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacassandra1-default
  namespace: default
  labels:
    app: cassandra
    namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/default/dotricorder03/data-cassandra-1