---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redissecondary0-default
  namespace: default
  labels:
    app: redissecondary
    namespace: default
    podindex: "0"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredissecondary-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redissecondary1-default
  namespace: default
  labels:
    app: redissecondary
    namespace: default
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredissecondary-1