---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redissentinel0-default
  namespace: default
  labels:
    app: redissentinel
    namespace: default
    podindex: "0"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredissentinel-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redissentinel1-default
  namespace: default
  labels:
    app: redissentinel
    namespace: default
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredissentinel-1