---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisprimary0-default
  namespace: default
  labels:
    app: redis-primary
    namespace: default
    comp-group: redis
    podindex: "0"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredisprimary-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisprimary1-default
  namespace: default
  labels:
    app: redis-primary
    namespace: default
    comp-group: redis
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/default/dotricorder03/data-dirredisprimary-1