---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-redissentinel-0
  namespace: default
  labels:
    app: redissentinel
    namespace: default
    podindex: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redissentinel
      namespace: default
      podindex: "0"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-redissentinel-1
  namespace: default
  labels:
    app: redissentinel
    namespace: default
    podindex: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redissentinel
      namespace: default
      podindex: "1"